app/FrontPage.js
app/nls/ApplicationError.js
app/nls/de/ApplicationError.js

Fixes https://phabricator.wikimedia.org/T101243, https://github.com/wmde/Lizenzverweisgenerator/issues/66

 Show an error message if no licence template has been recognized

---

app/Questionnaire.js

Use browser back and avoid strange errors mixing button- and browser-back.
When testing it seems to work fine for me. Can you give examples where the other version failed @wmde-manicki or @KaiNissen ?

changed back functionality of button

---

app/Application.js
app/Questionnaire.js
app/QuestionnairePage.js
app/QuestionnaireState.js
index.html
tests/app/QuestionnairePage.tests.js
tests/index.html

Would close https://github.com/wmde/Lizenzverweisgenerator/issues/21, https://phabricator.wikimedia.org/T101242, https://phabricator.wikimedia.org/T105161.
This pull request uses different approach than https://github.com/wmde/Lizenzverweisgenerator/pull/69 (uses Dojo/back library instead of History.js)

Handle browser back and forward buttons

---

app/AttributionGenerator.js

See: https://phabricator.wikimedia.org/T105803

bug fix: attribution missing authors name

---

redesign/css/main.css
redesign/data/background_images.json
redesign/index.html
redesign/js/background.js

Task on Phabricator: https://phabricator.wikimedia.org/T109470
Demo: http://tools.wmflabs.org/addshore-dev/ag/changing_background/redesign/
I didn't import all of the background images and attributions yet since they're in a Google Doc which makes it hard to extract the URLs and attributions. I'm hoping a CSV/plain text version exists somewhere :)

Show a different background picture every day.

---

redesign/css/main.css
redesign/index.html

Adds the feedback form (without backend).
Task on Phabricator: https://phabricator.wikimedia.org/T109475
Demo: http://tools.wmflabs.org/addshore-dev/ag/feedback_form/redesign/

Add feedback form.

---

redesign/css/main.css
redesign/index.html

UI improvements addressing https://phabricator.wikimedia.org/T111185#1637539
Demo: http://tools.wmflabs.org/addshore-dev/ag/improvements/redesign/

Small UI improvements.

---

redesign/css/main.css
redesign/index.html
redesign/js/scrolling_effects.js

Like #90 but for the text box :)
Demo: http://tools.wmflabs.org/addshore-dev/ag/textbox_scrolling/redesign/

Textbox scrolling

---

.jshintrc
redesign/css/main.css
redesign/js/main.js
redesign/js/scrolling_effects.js

Task on Phab: https://phabricator.wikimedia.org/T111187
This adds parallax scrolling effects to the start screen elements.
I rewrote most of the previous scrolling effects to use only two `ScrollMagic.Scene`s - one for scrolling up and one for scrolling down.

Scroll parallax

---

backend/.gitignore
backend/app.php
backend/composer.json
backend/config.example.php
backend/phpunit.xml.dist
backend/src/Actions/FeedbackAction.php
backend/tests/ApplicationTest.php
backend/tests/FeedbackActionTest.php
backend/web/index.php

Task on Phab: https://phabricator.wikimedia.org/T111191
The frontend will follow in a separate PR.

Feedback backend

---

backend/src/Actions/FeedbackAction.php
backend/tests/FeedbackActionTest.php
backend/web/.htaccess
redesign/css/main.css
redesign/index.html
redesign/js/main.js

This is the frontend for https://phabricator.wikimedia.org/T111191 as mentioned in #94.

Feedback frontend

---

redesign/css/main.css

Round all of the corners!!
Task on Phab: https://phabricator.wikimedia.org/T114892
Demo: http://tools.wmflabs.org/addshore-dev/ag/round_corners/redesign/

Make all the corners round.

---

redesign/js/app/AttributionDialogue.js
redesign/js/app/Dialogue.js
redesign/js/app/DialogueStep.js
redesign/tests/app/AttributionDialogue.tests.js
redesign/tests/app/Dialogue.tests.js
redesign/tests/app/DialogueStep.tests.js
redesign/tests/tests.js

Task on Phab: ~~https://phabricator.wikimedia.org/T106008 (I think?)~~ https://phabricator.wikimedia.org/T116915
This is dialogue logic only and does not include any UI functionality or add support for new licences.

Dialogue logic

---

redesign/css/main.css
redesign/index.html
redesign/js/app/templates/SmallButton.handlebars

Task on Phab: https://phabricator.wikimedia.org/T116000
+ some minor adjustments.

Design improvements

---

redesign/css/main.css
redesign/js/app/AttributionDialogue.js
redesign/js/app/LicenceStep.js
redesign/js/app/LicenceStore.js
redesign/js/app/templates/LicenceStep.handlebars
redesign/js/app/views/LicenceStepView.js
redesign/js/i18n.json
redesign/tests/app/AttributionDialogue.tests.js
redesign/tests/app/AttributionDialogueView.tests.js
redesign/tests/app/LicenceStore.tests.js

Task on Phab: https://phabricator.wikimedia.org/T116045
This adds the third and last substep to the editing section. This substep will show a list of compatible licences for the original image according to this table: https://docs.google.com/document/d/1SGu3kY0IRY0pvMxcGlXrpHJQNnThsApWGNzAVDX1eEY/edit#heading=h.8x5my3jcf6zt

Licence substep

---

redesign/css/main.css
redesign/js/app/views/DialogueEvaluationView.js
redesign/package.json

Task: https://phabricator.wikimedia.org/T106011
Demo: http://tools.wmflabs.org/file-reuse-test/copy_button/redesign/

Copy button

---

redesign/css/main.css
redesign/js/app/DialogueEvaluation.js
redesign/js/app/views/DialogueEvaluationView.js
redesign/js/i18n.json

Task: https://phabricator.wikimedia.org/T109568
Demo: http://tools.wmflabs.org/file-reuse-test/licence_button/redesign/

Add licence button.

---

redesign/css/main.css
redesign/js/app/templates/DialogueScreen.handlebars
redesign/js/app/templates/InfoBox.handlebars
redesign/js/app/views/AttributionDialogueView.js
redesign/js/app/views/InfoBoxView.js
redesign/js/i18n.json

Task1: https://phabricator.wikimedia.org/T116018
Task2: https://phabricator.wikimedia.org/T116010
Task3: https://phabricator.wikimedia.org/T116012
Demo: http://tools.wmflabs.org/file-reuse-test/info-boxes/redesign/

Info boxes

---

redesign/css/main.css
redesign/js/app/DialogueEvaluation.js
redesign/js/app/templates/DialogueScreen.handlebars
redesign/js/i18n.json
redesign/tests/app/DialogueEvaluation.tests.js

* removed strange blank space at the bottom of the front page
* made dialogue headline look nicer and made sure the scrolling animation does not cut anything off
* fixed two failing tests
* by accident found an image on commons that has no author and realised the attribution does not do what it's supposed. fixed that. (image is https://commons.wikimedia.org/wiki/File:Dison-Verviers-Fiacre-c.jpg)
* cleaned up a bit
* made sure the licence link is not covered by the menu bar
Demo: http://tools.wmflabs.org/file-reuse-test/small_improvements/redesign/

Small improvements

---

redesign/index.html

Demo link: https://tools.wmflabs.org/file-reuse-test/feedback-form-ids/redesign/ (althought there is not that much to demo there)
Apart from that IDE will not longer yell at me after those are added, clicking the label of form fields also inserts focus to the related text field.

Add ids to feedback form fields

---

redesign/css/main.css

Task: https://phabricator.wikimedia.org/T119628
Demo: https://tools.wmflabs.org/file-reuse-test/align-dont-track-text/redesign/

Fix alignment of the "do not track" checkbox label

---

redesign/js/app/LICENCES.js
redesign/tests/app/LicenceStore.tests.js

Task: https://phabricator.wikimedia.org/T118953
Demo:http://tools.wmflabs.org/file-reuse-test/fix_cc_by_sa_1/redesign/
Guys in chairs now work too: `https://commons.wikimedia.org/wiki/File:%22Stimmwerck%22_German_Renaissance_Vocal_Ensemble.jpg`

Fix CC BY-SA 1.0 detection.

---

redesign/index.html
redesign/js/i18n.json
redesign/js/main.js

Task: https://phabricator.wikimedia.org/T120098
Demo: https://tools.wmflabs.org/file-reuse-test/tracking-checkbox-text/redesign/

Update tracking disclaimer

---

.jscsrc
.jshintignore
.travis.yml
redesign/package.json
redesign/tests/app/AttributionDialogue.tests.js
redesign/tests/array-find.js

No demo link this time as it does not much of sense.
I still haven't figured out how to make "new" tests running in Firefox but at least running them headlessly turned out to be rather straightforward.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Browser_compatibility) the Array.prototype.find polyfill would be required to run tests in e.g. IE anyway.
https://github.com/wmde/Lizenzverweisgenerator/commit/8e0019f489f35e6bac3d0deb03c9e28ae3f7409d doesn't really belong here but I included it as well so dear reviewers don't have to look at changes to `.travis.yml` twice.

Run "new" tests on CI server

---

redesign/css/main.css
redesign/js/main.js

Two in one: https://phabricator.wikimedia.org/T120096 + https://phabricator.wikimedia.org/T120095
Demo: https://tools.wmflabs.org/file-reuse-test/adjust-feedback/redesign

Adjust feedback form and messages

---

redesign/js/app/LICENCES.js
redesign/tests/app/LicenceStore.tests.js

Task: https://phabricator.wikimedia.org/T119373#1847684
Demo: http://tools.wmflabs.org/file-reuse-test/final_licence_changes/redesign

Adjust compatible licences according to the latest changes.

---

redesign/js/app/templates/ImagePreview.handlebars
redesign/js/i18n.json

Demo: https://tools.wmflabs.org/file-reuse-test/download-link-i18n/redesign

Make download image link i18n-able

---

redesign/js/app/DialogueEvaluation.js
redesign/tests/app/DialogueEvaluation.tests.js

Task: https://phabricator.wikimedia.org/T120097
Demo: https://tools.wmflabs.org/file-reuse-test/no-title-cc4-print/redesign

Do not include title in attribution for use in print if the licence is CC4

---

redesign/js/app/InputHandler.js

Demo: http://tools.wmflabs.org/file-reuse-test/mobile_urls/redesign/
Task: https://phabricator.wikimedia.org/T120690#1861653

Support mobile URLs.

---

redesign/css/main.css
redesign/js/app/templates/ImagePreview.handlebars
redesign/js/app/views/DialogueScreen.js
redesign/js/i18n.json

Task: https://phabricator.wikimedia.org/T118743 (this is only about the first part of the description. I believe the latter part is already done)
Demo: https://tools.wmflabs.org/file-reuse-test/file-page-url/redesign

Add link to file page on Commons (below the download button)

---

redesign/js/app/ApplicationError.js
redesign/js/app/AttributionDialogue.js
redesign/js/app/Dialogue.js
redesign/js/app/FileForm.js
redesign/js/app/templates/ImagePreview.handlebars
redesign/js/app/views/DialogueEvaluationView.js
redesign/js/main.js

https://phabricator.wikimedia.org/T117414
This adds tracking to:
- Download button
- Copy button
- Start of the process (entering a URL) as well as the URL itself, as well as if it is a wikipage or direct image
- Errors encountered when trying to enter a URL
- Completion of every step of the process (using the step name)
- Completion of the process / landing on the final page

More tracking!

---

redesign/css/main.css
redesign/js/app/AttributionDialogue.js
redesign/js/app/Dialogue.js
redesign/js/app/templates/Dialogue.handlebars
redesign/js/app/templates/ProgressBar.handlebars
redesign/js/app/views/AttributionDialogueView.js
redesign/js/app/views/ProgressBarView.js
redesign/js/i18n.json
redesign/tests/TestHelpers.js
redesign/tests/app/AttributionDialogue.tests.js
redesign/tests/app/AttributionDialogueView.tests.js
redesign/tests/app/ProgressBarView.tests.js
redesign/tests/tests.js

Task: https://phabricator.wikimedia.org/T116159
Demo: http://tools.wmflabs.org/file-reuse-test/progress_bar_ui/redesign/

Progress bar ui

---

redesign/tests/app/ProgressBarView.tests.js

Fix broken tests for travis.

---

redesign/js/app/templates/Attribution.handlebars
redesign/js/view_helpers.js

Task: https://phabricator.wikimedia.org/T120949
Demo: https://tools.wmflabs.org/file-reuse-test/remove-target-blank/redesign/

Do not include target=_blank in HTML attribution

---

redesign/js/app/templates/Attribution.handlebars
redesign/js/app/views/DialogueEvaluationView.js
redesign/js/i18n.json
redesign/package.json

Task: https://phabricator.wikimedia.org/T106011
This one uses flash but works with Firefox, Safari and Chrome without any issues for me.
Demo: http://tools.wmflabs.org/file-reuse-test/copy_button/redesign/

Improve attribution copying

---

redesign/js/app/templates/Dialogue.handlebars
redesign/js/app/views/AttributionDialogueView.js

Task: https://phabricator.wikimedia.org/T121078
Demo: https://tools.wmflabs.org/file-reuse-test/fade-animation/redesign

Only animate bubble contents (including the bubble tip) in the dialogue.

---

redesign/css/main.css

Task: https://phabricator.wikimedia.org/T116159#1865390
Demo: http://tools.wmflabs.org/file-reuse-test/progress_bar_line_fix/redesign/

Remove the small lines sticking out at the top and bottom.

---

redesign/css/main.css

Made the bottom menu links white and improved their padding.
Demö: http://tools.wmflabs.org/file-reuse-test/prettify_bottom_menu/redesign/
Task: https://phabricator.wikimedia.org/T120951

Prettify bottom menu.

---

redesign/js/app/DialogueEvaluation.js
redesign/tests/app/DialogueEvaluation.tests.js

Task: https://phabricator.wikimedia.org/T121511
Demo: http://tools.wmflabs.org/file-reuse-test/author_attribution/redesign/
Example image: `https://commons.wikimedia.org/wiki/File:A_butterfly_feeding_on_the_tears_of_a_turtle_in_Ecuador.jpg`

Use author attribution provided by the user if it exists.

---

redesign/index.html

Task: https://phabricator.wikimedia.org/T120953
Demo: http://tools.wmflabs.org/file-reuse-test/no_submit/redesign/

Disable form submission without javascript being loaded.

---

redesign/js/app/views/AttributionDialogueView.js

Task: https://phabricator.wikimedia.org/T120947
Demo: http://tools.wmflabs.org/file-reuse-test/focus_input/redesign/

Automatically focus text fields in steps.

---

redesign/css/main.css

Task: https://phabricator.wikimedia.org/T121080
Demo: http://tools.wmflabs.org/file-reuse-test/inset_shadow/redesign/

Remove inset shadow from the progress bar.

---

redesign/css/main.css
redesign/js/app/FileForm.js
redesign/js/app/views/AttributionDialogueView.js

Task: https://phabricator.wikimedia.org/T120958
Demo: http://tools.wmflabs.org/file-reuse-test/done_alignment/redesign/
* decreased font size
* decreased image size to max 300px
* fixed alignment in the done section (it looked very narrow when aligned with the dialogue bubble)

Improve alignment of the done section.

---

redesign/css/main.css

Aligns the buttons with the attribution field in all browsers.
Demo: https://tools.wmflabs.org/file-reuse-test/align_buttons/redesign/

Correctly align attribution buttons.

---

redesign/css/main.css

Task: https://phabricator.wikimedia.org/T121086
Demo: https://tools.wmflabs.org/file-reuse-test/pop-up-shadow/redesign/

Add shadow to modal pop-ups

---

redesign/index.html

Task: https://phabricator.wikimedia.org/T121682
Demo: https://tools.wmflabs.org/file-reuse-test/labs-terms-of-use/redesign/

Add a note to the Legal Notice saying that tool is hosted on WM Labs

---

js/i18n.json

Task: https://phabricator.wikimedia.org/T121764

Change private use info box text.

---

backend/src/Actions/FeedbackAction.php
index.html
js/i18n.json

Task: https://phabricator.wikimedia.org/T122798

Change texts.

---

index.html

Task: https://phabricator.wikimedia.org/T122800
Demo: https://tools.wmflabs.org/file-reuse-test/wikimedia.de-links/

Add links to wikimedia.de website

---

css/main.css
js/app/FileForm.js
js/app/Spinner.js
js/main.js

Task: https://phabricator.wikimedia.org/T120952
Demo: http://tools.wmflabs.org/file-reuse-test/loading_spinner/
Instruction: There is one loading spinner on the "Los!" button when submitting any image, another when loading a Wikipedia page (e.g. `https://de.wikipedia.org/wiki/Eichhörnchen`) when clicking on a picture and also one for the submit button on the feedback form.

Loading spinner

---

README.md

Not a code change but I think it still makes sense that someone else looks at this, maybe there is more to adjust in the README.

Do not promise too much in README

---

js/app/Api.js

PHPStorm was kind to point out this interesting piece of code.

Change a one-iteration loop into a condition

---

js/app/FileForm.js

Task: https://phabricator.wikimedia.org/T132670

Track user input with Start event even when it errors.

---

index.base.html
index.php
js/main.js

Another try from a reseted version

Prefill input field with url parameter. Start the process automatically.

---

i18n/de/legal.html
i18n/en/legal.html

Change from Christian Rickerts to Abraham Taherivand.

Updating ED in legal.html

---

css/main.css

Per [T121073](https://phabricator.wikimedia.org/T121073).

Changing hover color for image selection

---

js/app/Api.js
js/app/InputHandler.js
tests/LocalApi.js
tests/app/InputHandler.local.tests.js
tests/fixtures/titles/10391.json
tests/fixtures/titles/118613.json
tests/fixtures/titles/15382769.json
tests/fixtures/titles/45093094.json

Bug: [https://phabricator.wikimedia.org/T157434](T157434)

Handle URLs containing page ID (curid) instead of title.

---

js/app/DialogueEvaluation.js

Cherry-picked from https://github.com/wmde/Lizenzhinweisgenerator/commit/dd36e134cfdd9149c3c5feab686ed0467daf6f9d

Dont show public domain snippet when image was edited

---

i18n/es/i18n.json

Hi,
I had a mistake, I have fixed it. It is only a word but with an important spelling error.
* «empecémos» > «empecemos»
Excuse me!
Regards,
Iván

Important spelling fixing

---

index.php

Until we got the OK from the lawyer

Temporarily disable Ukrainian translation

---

i18n/uk/legal.html

"personal data" sentence translated

+translation
