wmde/Lizenzhinweisgenerator

- .gitignore
- .travis.yml
- README.md
This is a pull request onto `mock-api-in-tests`, as I see this change as a part of improving the testing of the code. I can change this to be a change against master, if preferred.
I suggest using https://github.com/jonkemp/qunit-phantomjs-runner as it is more flexible than https://github.com/jonkemp/node-qunit-phantomjs we've been using so far. Namely, the former allows to change the timeout of the test run, which might be required when testing methods making API calls.
Moreover, the latter runner is actually only a simple wrapper over the qunit-phantomjs-runner.
Note: I have intentionally NOT set TravisCI to run `tests/api-tests.html`. I am not sure whether we want to make bunch of calls to Commons API whenever change is pushed to the repository. I believe "local" API tests should be …
> Change test runner to qunit-phantomjs-runner

- app/FrontPage.js
- app/InputHandler.js
- app/WikiAsset.js
- app/WikiAssetPage.js
- tests/app/Api.tests.js
- tests/app/AttributionGenerator.tests.js
- tests/app/InputHandler.local.tests.js
- tests/app/InputHandler.tests.js
- tests/app/WikiAsset.tests.js
- tests/assets.js
- tests/index.html
This is a pull request onto `mock-api-in-tests`, as I see this change as a part of improving the testing of the code. I can change this to be a change against master, if preferred.
The background here is that tests making AJAX calls to Commons/Wikipedia APIs have been falling when run from command line (as pointed out in https://phabricator.wikimedia.org/T107023). The reason of these failures is PhantomJS understanding "protocol-relative" urls to APIs differently than "real" browser (namely, PhantomJS attempts to read local files when given such urls).
Apart from this issue, I think it is rather redundant to use protocol-relative URLs when Commons and Wikipedias are actually always offering access using HTTPS. Therefore I think it makes more sense to explicitly use https-prefixed URLs to …
> Use https in Commons/Wikipedia URLs explicitly

- app/WikiAssetPage.js
Fixes: https://phabricator.wikimedia.org/T108029
Passing empty attribution element caused an infinite loop
> While trimming empty nodes of the template, check if current element is not empty

- index.html
JSCS 2.2.0 is also linting JS in HTML files what was causing odd failures of Travis builds.
> Fix indentation and spacing in index.html

- redesign/index.html
- redesign/js/i18n.json
- redesign/js/main.js
This only changes the text and uses a checkbox instead of the link as mentioned here: https://phabricator.wikimedia.org/T116587#1824688
Task: https://phabricator.wikimedia.org/T116587
Demo: http://tools.wmflabs.org/file-reuse-test/cookie_tracking_update/redesign/
> Cookie tracking update

- redesign/js/app/DialogueEvaluation.js
- redesign/tests/app/DialogueEvaluation.tests.js
Task: https://phabricator.wikimedia.org/T119625
Demo: http://tools.wmflabs.org/file-reuse-test/fix_author/redesign/
Example image: `https://commons.wikimedia.org/wiki/File:%22Le_Tour_de_France%22,_a_cartoon_sequence_Wellcome_L0053073.jpg`
> Add user input for author to the attribution.

- redesign/index.html
- redesign/js/app/views/AttributionDialogueView.js
- redesign/js/i18n.json
Task: https://phabricator.wikimedia.org/T116022
Demo: https://tools.wmflabs.org/file-reuse-test/private-use-box/redesign/
Remarks:
- defining the colour of links would be shared with https://github.com/wmde/Lizenzverweisgenerator/pull/143, so I haven't duplicated it here,
- same as in https://github.com/wmde/Lizenzverweisgenerator/pull/143 links in the box open in the new window,
- please comment if opening the additional information on private use should NOT be tracked (I assumed it should as it is already done with other pop-up boxes),
- given the remark above, I haven't tested if this particular tracking works as I haven't set up the Piwik instance for AG yet. Verifying it would be great.
> Add pop-up box with more private-use information

- redesign/js/app/templates/InfoBox.handlebars
- redesign/js/app/views/InfoBoxView.js
Task: https://phabricator.wikimedia.org/T119627
Demo: https://tools.wmflabs.org/file-reuse-test/ported-no-close/redesign/
I've tested it with `https://commons.wikimedia.org/wiki/File:Timo-Juurikkala2004.jpg` licensed on the ported version of CC-BY-1.0 (first ported license from the list).
I'm not sure at what level not adding the close button should be actually done, so it might be that this first attempt is not the right one.
> Do not add closing X button to the ported license info box

- redesign/css/main.css
Task: https://phabricator.wikimedia.org/T118954
Demo: https://tools.wmflabs.org/file-reuse-test/how-it-works-more-responsive/redesign/
I am not sure how big those icons should actually be on really big screens. Maybe even bigger than now.
Also made those images smaller on smaller screens, where the text could be a bit smaller (at least it looked like this for me when I made a window small).
Has this thing been designed by Mr. UX Expert?
> Adjust the size of images and text in the "How it works" screen to the size of the screen

- redesign/js/app/LICENCES.js
- redesign/js/app/Licence.js
- redesign/js/app/LicenceStep.js
- redesign/js/app/LicenceStore.js
- redesign/tests/app/AttributionDialogueView.tests.js
- redesign/tests/app/LicenceStore.tests.js
This adds the CC BY-SA 1.0 licence and also changes the compatible licences according to the adjustments in the specification.
Task1: https://phabricator.wikimedia.org/T119373
Task2: https://phabricator.wikimedia.org/T118953
Demo: 
**Instructions for task 1**: Enter and submit `https://commons.wikimedia.org/wiki/File:%22Лунг%22_Заказник_ландшафтний1.JPG` (CC BY 1.0), click through to the licence step (make sure to click "Ja" in the editing step). There should now no longer be any SA licences other than the 1.0 in the list of compatible licences. The same goes for the other cases where things were changed!
**Instructions for task 2**: Enter and submit `https://commons.wikimedia.org/wiki/File:Cinnamomum_Verum_vs_Cinnamomum_Burmannii.jpg` (CC BY-SA 1.0). There should not be any error
> Change licences

- redesign/js/app/DialogueEvaluation.js
- redesign/tests/app/DialogueEvaluation.tests.js
Demo: https://tools.wmflabs.org/file-reuse-test/author-links-target/redesign
Noticed that author links in attribution don't get `target` attribute while licence and title links do. Adding this for sake of consistency.
Changed the name of the test author as there seems to be some Commons user called "Meh" already.
> Open author links in new window

- redesign/js/app/views/DialogueEvaluationView.js
Task: https://phabricator.wikimedia.org/T118743 (2nd part)
Demo: https://tools.wmflabs.org/file-reuse-test/licence-name-in-link/redesign/
> Show the licence name in the link to the full text of the licence

- redesign/css/main.css
- redesign/js/app/AttributionDialogue.js
- redesign/js/app/Dialogue.js
- redesign/js/app/views/AttributionDialogueView.js
- redesign/js/app/views/ProgressBarView.js
- redesign/tests/TestHelpers.js
- redesign/tests/app/AttributionDialogueView.tests.js
- redesign/tests/app/ProgressBarView.tests.js
! Don't merge yet !
Task: https://phabricator.wikimedia.org/T116160
Demo: http://tools.wmflabs.org/file-reuse-test/progress_bar_back/redesign/
Going back by clicking progress bar items should work correctly with this patch.
The browser back functionality is where it gets a little bit tricky and I'm not sure my approach is going in the right direction. The way it is implemented here already sort of works but there are some ugly parts e.g. the forward button breaks everything and I'm pretty sure I'm pushing too many things onto the history.
Hoping to get insights from experienced browser history experts ... @wmde-manicki!? :D
> Progress bar back

- redesign/js/app/DialogueEvaluation.js
- redesign/js/app/templates/Attribution.handlebars
- redesign/js/app/views/DialogueEvaluationView.js
- redesign/tests/app/DialogueEvaluation.tests.js
Task: https://phabricator.wikimedia.org/T119065
Demo: https://tools.wmflabs.org/file-reuse-test/plain-plain-text-attribution/redesign/
This remove not wanted hyperlinks from plan text attribution (which is now really a plain text).
This also adds quote marks to print attribution. I could leave it out if this is not intended but e.g. old version had those.
> Do not include <a> tags in the "plain text attribution"

- redesign/css/main.css
- redesign/js/app/templates/AuthorStep.handlebars
- redesign/js/app/templates/ChangeStep.handlebars
- redesign/js/app/templates/CompilationStep.handlebars
- redesign/js/app/templates/EditingStep.handlebars
- redesign/js/app/templates/LicenceStep.handlebars
- redesign/js/app/templates/TypeOfUseStep.handlebars
Task: https://phabricator.wikimedia.org/T120948
Demo: https://tools.wmflabs.org/file-reuse-test/form-fields-alignment/redesign
> Align checkbox in dialogue form better and don't add extra line break in edit subsection

- js/app/DialogueEvaluation.js
- js/app/WikiAssetPage.js
Task: https://phabricator.wikimedia.org/T121511
Demo: http://tools.wmflabs.org/file-reuse-test/improve_attribution_scraping/
It should now get the correct attribution for files like `https://commons.wikimedia.org/wiki/File:ChineseLimmat.jpg` (attribution in the summary table) and `https://commons.wikimedia.org/wiki/File:Flughahn.jpg` (attribution contains HTML)
> Improve attribution scraping

- js/app/views/ProgressBarView.js
- tests/app/ProgressBarView.tests.js
Task: https://phabricator.wikimedia.org/T122795
Demo: http://tools.wmflabs.org/file-reuse-test/substep_fix/
Enter `https://commons.wikimedia.org/wiki/File:Karl-Marx-Allee_Frankfurter_Tor_Turm_Schild.jpg`. "Bearbeitung" should not be a substep anymore now.
> Fix isSubstep logic.

- js/app/InputHandler.js
- tests/app/InputHandler.local.tests.js
Task: https://phabricator.wikimedia.org/T122799
Demo: https://tools.wmflabs.org/file-reuse-test/url-params/
Try e.g. `https://commons.wikimedia.org/wiki/File:Karl-Marx-Allee_Frankfurter_Tor_Turm_Schild.jpg?uselang=de` as an input
> Ignore GET params when parsing the input URL

- js/i18n.json
Task: https://phabricator.wikimedia.org/T123466
Demo: https://tools.wmflabs.org/file-reuse-test/pd-msg
Note: Phabricator task states "For all CC-0 and PD-Templates the text should be as follows:" whereas currently that text has been only shown for PD stuff, CC-0 goes through the steps as other recognized licences. I don't know if whether this is still OK, so I am making this remark here.
> Change Public Domain information text

- js/app/LICENCES.js
- tests/app/LicenceStore.tests.js
Task: https://phabricator.wikimedia.org/T123465
Demo: https://tools.wmflabs.org/file-reuse-test/copyrighted-free-use-licence
Test with e.g.: https://commons.wikimedia.org/wiki/File:Blaikiewell_snowdrops.jpg or https://commons.wikimedia.org/wiki/File:02_meidum_pyramid.jpg.
I am not sure what licence is this "Copyrighted free use" template actually referring to. As might be seen using the demo URL, currently it is CC-0 (as commons template sort of suggests, not the PD). But I have no idea whether it is at all OK. This would be changed accordingly once someone with knowledge has commented.
> Recognize "Copyrighted free use" licence template

- js/app/views/DialogueScreen.js
- tests/app/DialogueScreen.tests.js
- tests/tests.js
Task: https://phabricator.wikimedia.org/T123625
Demo: https://tools.wmflabs.org/file-reuse-test/no-attribution-cc0/
examples: `https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg` (PD template), `https://commons.wikimedia.org/wiki/File:%22Bisonte_a_la_vista%22_%282%29.jpg` (cc-zero)
See also: https://github.com/wmde/Lizenzverweisgenerator/pull/199#issuecomment-171586077
> Show information on no attribution required instead of dialogue for pictures with cc-zero template

- js/app/Api.js
- js/config.json
- tests/LocalApi.js
Task: https://phabricator.wikimedia.org/T123520
Demo: https://tools.wmflabs.org/file-reuse-test/api-continuation/
The problem that has been discovered using: `https://commons.wikimedia.org/wiki/File:Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg`. The page of that file has some 147 templates or so, while the tool has been only fetching 100 templates. That was usually OK but as the licence templates of the Mona Lisa didn't make it in the first hundred, the tool assumed there is no known licence template, and showed the relevant error message.
The quick fix would be probably increasing the number of templates fetched for a page (API's limit being 500) but I doubt it is a way to go. API offers a possibility to continue the previous query if number of stuffs to return is bigger …
> Get all the templates

- css/main.css
- js/app/templates/Dialogue.handlebars
- js/app/templates/PublicDomain.handlebars
- js/app/views/DialogueEvaluationView.js
Task: https://phabricator.wikimedia.org/T123737
Demo: https://tools.wmflabs.org/file-reuse-test/pd-bubble/
Tested in Firefox and Chromium so far.
CSS table display [wouldn't work in IE 7](http://caniuse.com/#feat=css-table) but this is not the IE version that should be supported, right?
https://github.com/wmde/Lizenzverweisgenerator/commit/8154f049ee62e2e13e5e95e6e9d890adca31eff9 is not directly related to the change requested in the phab task but after doing other changes I have noticed that evaluation view is broken as all stuff below the dialogue "Done" message (in the bubble) is put into the same row as the the bubble (due to those other elements being chidren of the `dialogue-bubble` `<div>`). I guess this is not correct (compare also `<div>` structure in the PD view). I can also …
> Do not include progress bar placeholder in the PD information view

- js/app/Api.js
- tests/app/InputHandler.local.tests.js
- tests/fixtures/images/Lars_Kindgen.json
- tests/fixtures/metadata/Lars_Kindgen.json
Task: https://phabricator.wikimedia.org/T124760
Demo: https://tools.wmflabs.org/file-reuse-test/no-images-error-msg/
Sample input:
`https://de.wikipedia.org/wiki/Lars_Kindgen`
`https://fr.wikipedia.org/wiki/Aide:Comment_cr%C3%A9er_un_article`
Redirects are also considered by tool as pages with no images, see e.g. `https://de.wikipedia.org/wiki/Tschunk`
Combined with https://github.com/wmde/Lizenzverweisgenerator/pull/207 would also show an error message for things like `https://commons.wikimedia.org/wiki/Commons:Contact_us`
> Show error message when there is no images in the wiki page instead of doing nothing.

- js/app/Api.js
- js/app/InputHandler.js
- tests/app/InputHandler.local.tests.js
- tests/fixtures/imageinfo/Anime-Cosplay 14.JPG.json
- tests/fixtures/images/Seeteufel.json
- tests/fixtures/metadata/A_Punjab_Village,_1925.webm.json
- tests/fixtures/metadata/Anime-Cosplay_14.JPG.json
- tests/fixtures/metadata/Seeteufel.json
Task: https://phabricator.wikimedia.org/T123914
Demo: https://tools.wmflabs.org/file-reuse-test/all-from-commons/
Boring description what this change is about:
- currently Commons URLs have been treated differently than Wikipedia URLs etc in that manner that if Commons URL has been an input than it has been assumed that it is a file page URL, and API has been asked to provide the media/image info. For Wikipedia URLs API first checks if the URL contains any media (ie. if it is a file page), and if not images contained by the page (e.g. pictures in the wikipedia article) are fetched through API.
- this reasoning lead to the problem described in the Phabricator ticket: when other Commons URL than file page has been inserted unpredictable things happened: sometimes tool has shown an error …
> Handle other Commons URLs than file page 

- js/app/FileForm.js
- js/main.js
Demo: https://tools.wmflabs.org/file-reuse-test/dismiss-error-gallery/
To see what this is about (on [master](https://tools.wmflabs.org/file-reuse-test/dismiss-error-gallery/)):
- enter `https://de.wikipedia.org/wiki/DFB-Pokal`,
- when images have loaded, click the UEFA logo,
- error message regarding image's licence appears,
- click Commons logo,
- screen scrolls down and shows information about PD usage of Commons logo,
BUT: once you scroll back up to the input field the error message is still there. That might be confusing for the user
> Hide the error message after selecting the image from the "gallery"

- js/app/Api.js
Task: https://phabricator.wikimedia.org/T124756
Demo: https://tools.wmflabs.org/file-reuse-test/moar-images/
So this is about changing two things:
- getting a complete list of images in the article by using `imcontinue` parameter of API query
- getting image infos (thumbnail, description page url etc) in series of max. 50 images at a time. API only accept 50 "titles" in single query and simply drops all above 50. 
Some tests cases:
- `https://fi.wikipedia.org/wiki/Jääkiekon_nuorten_maailmanmestaruuskilpailut_2016` - it has 54 images, without the latter part of the change only 50 images have been displayed.
- `https://de.wikipedia.org/wiki/DFB-Pokal_1976/77` - this has 126 images, so it actually makes use of both parts of the change. With only former only 76 images would be displayed. With …
> Get all the images from an article

- js/app/Api.js
Task: https://phabricator.wikimedia.org/T124759
Demo: https://tools.wmflabs.org/file-reuse-test/page-missing-error-msg/
Sample input:
`https://commons.wikimedia.org/wiki/SuperMegaAwesome.jpg`
`https://de.wikipedia.org/wiki/Jimmy_Naked`
Combined with https://github.com/wmde/Lizenzverweisgenerator/pull/207 would also show the message for `https://commons.wikimedia.org/wiki/User:Christoph_Fischer_%28WMDE%29`
> Show error message if wiki page is missing

- js/tracking.js
Silly me, missed the protocol in https://github.com/wmde/Lizenzverweisgenerator/pull/215 which breaks tracking (without the protocol part tool is trying to load something like `https://www.foo.bar/www.foo.bar/piwik/piwik.php`)
Still, I wonder why that change seemed to work for me when I tested it locally
Forcing HTTPS in the setting, not asking for `window.location.protocol` in case it happened to be http for whatever reason.
> Include protocol in the Piwik URL

- index.html
As suggested in the Phabricator ticket: https://phabricator.wikimedia.org/T130201
Demo: https://tools.wmflabs.org/file-reuse-test/inputmode-url/
It does not seem to have a desired phone but maybe it is just because I am using an old Schrott.
I am looking forward to hearing from reviewers if their mobile devices benefit from this change.
> Add input mode hint to the URL text fields

- js/app/InputHandler.js
- tests/app/InputHandler.local.tests.js
This is mostly about task: https://phabricator.wikimedia.org/T134742
While looking at this bug I realized that when given mobile Wikipedia URL the tool makes its first API request to "mobile" API URL (`https://en.m.wikipedia.org/w/api.php`) and further requests to non-mobile API URL. It is not a big deal I think but why not make the tool always talk to non-mobile API? This is why I added https://github.com/wmde/Lizenzhinweisgenerator/commit/f82c48007dcca36eb9bf187bbf689d580ca0cbae here.
I also found really small but quite silly inconsistency resulting from the thing described above. When given `https://de.wikipedia.org/wiki/Datei:1_FC_Bamberg_-_1_FC_N%C3%BCrnberg_1901.jpg` the link to the file on Commons (BTW: we should think about changing this text, as e.g. this file is not on Commons!) …
> Accepts mobile Commons URLs and some minor improvements regarding mobile Wikipedia URLs

- i18n/en/i18n.json
Taken out from https://github.com/wmde/Lizenzhinweisgenerator/pull/230
Thanks @Cladis and @AtaZh!
> Fix typo in download the image link

- index.base.html
- index.php
Following up https://github.com/wmde/Lizenzhinweisgenerator/pull/233, a small fix: do not generate HTML from PHP. Not a big deal in this case but I think it is good in general to avoid doing this if possible.
Pinging @martinkraft
> Do not generate HTML when url provided as GET param

- css/main.css
- images/wmde_logo.svg
Following up , let's use WMDE's own current logo. This way we're 100% exactly the right logo is used.
The logo is from WMDE "style guide". I've just cropped the original SVG slightly to fit the UI.
> Update the WMDE logo with the one from WMDE's style guide

- js/app/DialogueEvaluation.js
- tests/app/DialogueEvaluation.tests.js
When the editing attribution is empty, no comma should be appended.
> T182666 Fixed duplicate comma bug
